### ISSUE TITLE
Error in data_load.R

### ISSUE THREAD

**Issue by BErfanian** [MarkJBrewer/PlateauPaper#1]
Dear Mark,
In running the data_load.R scripts, the following error was generated:
"Error in geodDist(lon1 = AFEData.long, lat1 = AFEData.lat, lon2 = ClimateData$long[i],  : 
  unused arguments (lon1 = AFEData.long, lat1 = AFEData.lat, lon2 = ClimateData$long[i], lat2 = ClimateData$lat[i])"

This error was generated after running this section:

if(file.exists("Data/AFE.List.Mapping.RData")) {
    load("Data/AFE.List.Mapping.RData")
}else{
    Future.List.2045 <- list()
    for(i in 1:num.AFEData){
        Future.List.2045[[i]] <- 1
    }
    for(i in 1:num.ClimateData){
        Future.List.2045[[which.min(geodDist(lon1=AFEData.long,lat1=AFEData.lat,lon2=ClimateData$long[i],lat2=ClimateData$lat[i]))]] <- c(Future.List.2045[[which.min(geodDist(lon1=AFEData.long,lat1=AFEData.lat,lon2=ClimateData$long[i],lat2=ClimateData$lat[i]))]],i)
    }
    # Now set up future climate data for projections:
    for(i in 1:num.AFEData){
        Future.List.2045[[i]] <- Future.List.2045[[i]][-1]
    }
    if(!file.exists("Data/")) dir.create("Data/")
    save(Future.List.2045,file="Data/AFE.List.Mapping.RData")
}

----
Regards.

**Comment by MarkJBrewer** [comment]
Fixed, thanks.
